import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center p-24 gap-20">
      <div className="w-1/2 space-y-10">
        <section className="space-y-2">
          <h1 className="text-4xl font-bold">AI-generated Tags from a URL</h1>
          <p className="text-lg text-gray-600">
            This is a simple form that takes a URL and returns a list of tags
            generated by an AI model.
          </p>
        </section>

        <form className="space-y-4 border border-black rounded-lg p-6">
          <div className="">
            <Label htmlFor="url">URL</Label>
            <Input id="url" type="url" />
          </div>

          <Button type="submit">Generate Tags</Button>
        </form>
      </div>

      <div className="border border-black rounded-lg p-6 w-1/2">
        <h2 className="text-2xl font-bold">Tags</h2>
      </div>
    </main>
  );
}
